Event type title  not clear for system/model performance
adi-gini/ui pull request #15
Opened 2024-12-26 09:09 UTC by adi-gini

*Jira link:*
https://iguazio.atlassian.net/browse/ML-8820

<img width="422" alt="Screenshot 2024-12-26 at 11 02 20" src="https://github.com/user-attachments/assets/4e165ccb-a1b2-44f5-8f6f-4a3e931d68c6" />

2025-01-14 13:35 UTC, mariana-furyk commented on src/scss/main.scss
> +      width: 225px !important;
not the best way to add important styles, please check if we can handle it another way

2025-01-16 16:16 UTC, adi-gini commented on src/scss/main.scss
> +      width: 225px !important;
Done

2025-01-20 16:28 UTC, mavdryk requested changes

2025-01-20 16:28 UTC, mavdryk commented on package.json
> -    "iguazio.dashboard-react-controls": "2.2.11",
revert this change

2025-01-20 16:54 UTC, adi-gini commented on package.json
> -    "iguazio.dashboard-react-controls": "2.2.11",
Done

2025-01-21 09:48 UTC, mavdryk approved these changes

2025-01-21 10:17 UTC, closed without merging